### ISSUE TITLE
[QA] Teleporting may cause the platform to freeze

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3664] opened 2022-12-02 09:51 UTC
**Description:**
The game may permanently freeze after using various methods to teleport around the map multiple times. The issue seems to be more prone to occur, when teleporting to specific locations from the Explorer menu.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Use the Explorer menu to teleport around the world multiple times.
3. Observe the issue.

**Reproduction rate:**
3/5

**Results:**
Teleporting multiple times during one session causes the platform to freeze.

**Expected results:**
The platform is stable at all times.

**Notes:**

- The issue was reproduced on both the guest and wallet accounts.

- The issue was reproduced on both the production and development branches.

- Please see the attached video and log for reference: https://images.zenhubusercontent.com/337227404/ecdd3fa4-c6c3-4205-966f-259f923f7fc0/_3664.mp4, [https://app.zenhub.com/files/337227404/1169fccc-3ffb-4321-a47a-79833b148f18/download](https://app.zenhub.com/files/337227404/1169fccc-3ffb-4321-a47a-79833b148f18/download).

- Platforms: Web client.

**Comment by 0xD-Fabio** [comment] 2022-12-29 16:21
The error chain appears after 3 to 10 teleports in crowded areas after waiting a while to load every resource needed in the scene.

The errors appear in this sequence:
WebGL Uncaught RangeError "Failed to execute 'texSubImage2D' on 'WebGL2RenderingContext': The ArrayBuffer/ArrayBufferView size exceeds the supported range.

And then:
"The PlayerLoop internal function has been called recursively. Please Contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it."

See attached screenshots.

![WebGlLoading Abnormal playerLoop.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/df1cc184-d9e1-4467-8182-f3cf4f481ce5)![WebGlLoading Abnormal playerLoop - 2.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/0eb57b8d-9891-402f-87a9-05246526a499)

I've tried those things:

- [ ]  Update to the current latest Unity LTS 2021.3.16f1: no difference
- [ ]  Downgrade to the last commit before Unity 2021.3: The bug started occurring exactly when we upgraded to 2021.3

- [ ]  Change build compression method from Gzip to Brotli: not viable since CI takes way too long to build

- [ ]  Do a ton of research about these errors but didn't find more than what I already wrote.

- [ ] Last not tested (is more of a vague idea) is that this error may be related to texture loading from asset bundles, and the first of the two errors may happen because we try to load a huge texture, or a texture isn't a power of 2

**Comment by kwsskulinski** [comment] 2023-02-24 15:16
Issue no longer exists. Closing.

**Closed by kwsskulinski** 2023-02-24 15:16 UTC
Labels: bug, critical, stream-core
