### ISSUE TITLE
After using movePlayerTo the performance drops

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/unity-renderer#125] opened 2020-09-29 16:28 UTC
I found a small issue with `movePlayerTo` , after using it the performance drops (using it more than one time don't make it worse, the effect does not accumulate)

Tested on Chrome, GNU/Linux, using the latests ECS version 6.6.0

Before:
![Selección_999(1030)](https://user-images.githubusercontent.com/172656/94585984-156ff080-0257-11eb-9997-a433284d2de7.png)

After:
![Selección_999(1031)](https://user-images.githubusercontent.com/172656/94586012-1dc82b80-0257-11eb-8f3d-7f0ff2d0b13e.png)

Code:
```
const respawner = new Entity()
respawner.addComponent(new BoxShape())
respawner.addComponent(new Transform({ position: new Vector3(8, 0, 8) }))
respawner.addComponent(
  new OnPointerDown(
    (e) => {
      movePlayerTo({ x: 1, y: 0, z: 1 }, { x: 8, y: 1, z: 8 })
    },
    { hoverText: "Move player" }
  )
)

engine.addEntity(respawner)
```

Test scene, in case that portion of the code is not enough to reproduce the issue:
[slow_after_teleport.zip](https://github.com/decentraland/explorer/files/5300471/slow_after_teleport.zip)

**Comment by nearnshaw** [comment] 2021-04-15 13:24
If this is still happening, it should be very high priority!

We plan having players teleporting within the first few seconds of their experience in genesis plaza, so it would be a really bad first impression!

**Comment by sandrade-dcl** [comment] 2021-07-12 16:31
Hi @EibrielInv! We're trying to reproduce this issue but we cannot reproduce it (at least with the current SDK version). In order to confirm is it could be something already fixed on latest versions, could you try it again and confirm us is the problem is still happening? If it still happens, we will have to take a look more in deep. Thank you Eibriel! :)

**Comment by sandrade-dcl** [comment] 2021-07-15 13:14
Can't reproduce.

**Closed by sandrade-dcl** 2021-07-15 13:14 UTC
Labels: bug, major, need validation
