### ISSUE TITLE
Executing jumpin button in the same parcel freezes the loading

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3039] opened 2022-09-14 17:17 UTC
Repro steps:
1. Go to the same parcel where your friend is
2. Open the friends menu
3. Click the jump in button
4. The loading freezes

**Comment by JorgeDecentraland** [comment] 2022-09-21 11:53
@kwspgoliasz @kwssbocian could you try to reproduce this issue, please?

**Comment by kwssbocian** [comment] 2022-09-21 14:32
Hi, we've managed to reproduce this in both prod and dev. Issue occurs when using the Join button as well as the /goto command and the coords of the same or an adjacent tile the player is currently standing on. This causes the loading screen to get stuck. Most of the time while in the loading screen using movement keys causes the loading screen to disappear. However sometimes, seemingly at random, the loading screen gets stuck completely without any option to make it disappear.

**Comment by m3taphysics** [comment] 2022-12-14 10:34
Closing as dupe of: https://github.com/decentraland/unity-renderer/issues/3664

**Closed by m3taphysics** 2022-12-14 10:34 UTC
Labels: stream-baus
