### ISSUE TITLE
Message on top of the 'nearby' channel overlaps with the Profile menu

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2982] opened 2022-09-07 11:03 UTC
**Description:**
Opening other user's Profile menu from a message located below the chat notification on top of the 'nearby' channel, results in part of the menu getting hidden behind the message. Reproducing the issue requires at least two users to log into the platform.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Have other users write on the nearby channel until the messages reach the upper part of the chat.
3. Right-click on the received message to show the Profile menu.
4. Observe the issue.

**Results:**
The Profile menu is partially concealed by the notification on top of the 'nearby' channel.

**Expected results:**
The Profile menu is displayed over the notification on top of the chat.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/8a79b6f3-4b98-435e-8afb-d7c2df2a8369/_2982.mp4.

- Platform: Web Client, Windows Desktop Client.

**Comment by popuz** [comment] 2022-09-09 14:13
This issue can be reproduced in-editor much simpler: 
1. in-editor Right-click on the ChatController Component **(1)** attached to the Main GameObject
2. choose Fake Private Message several times **(2)**
3. step 3 from original "Steps to reproduce" in this report (see above)
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/9449c87f-df2c-4e01-b12d-6118a5c1c138)

**Comment by popuz** [comment] 2022-09-09 14:22
Issue caused by the **DescriptionContainer** (1) being lower in Hierarchy than **UserContextMenuPanel** (2). It is also overlays **ConfirmationDialog**.
There are 2 solutions:
1. We can just move **DesctiptionContainer** inside **Chat** (3) hierarchy above the **UserContextMenuPanel** and the **ConfirmationDIalog**. 
2. We can add Canvases to the **DesctiptionContainer**,  **UserContextMenuPanel**, **ConfirmationDIalog** and play with the overriding Sorting Layers. 
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/1568fdbd-fc49-4086-9065-189fcf1febae)

**Comment by popuz** [comment] 2022-09-14 14:44
resolved in the https://github.com/decentraland/unity-renderer/tree/feat/channels

**Closed by popuz** 2022-09-14 14:44 UTC
Labels: bug, minor
