### ISSUE TITLE
Invisible avatar in sdk6/sdk7 test scenes and playground

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#5223] opened 2023-05-22 15:45 UTC
When opening

- https://playground.decentraland.org/?
- https://sdk-test-scenes.decentraland.zone/?position=73,-8&realm=LocalPreview
- https://sdk-test-scenes.decentraland.zone/?position=-1,27&realm=LocalPreview

You get an insivible avatar, and the same error is present in all link

![image.png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/50aa06e4-4f10-4649-8ea0-e740c2da89ff)

![image.png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/ad68d22c-1fa9-4233-bb5f-bc2ad0e7f0a1)

![image.png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/ae5dee94-07e2-4f70-8a06-c95992e30c9d)

**Comment by kwssbocian** [comment] 2023-06-23 12:05
Cannot reproduce as of today using the provided links. In all cases the avatar appeared correctly with all of its wearables and never as a hologram
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/77cc8e37-6657-4c82-a363-acc389367565)
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/999b468e-991b-430d-8845-662b62989312)
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/27b4c908-eb59-4d0d-b48d-ad495812338b)

**Comment by kwssbocian** [comment] 2023-07-19 10:55
Cannot reproduce - issue no longer occurs. Closing

**Closed by kwssbocian** 2023-07-19 10:55 UTC
Labels: need validation, stream-core
