### ISSUE TITLE
[QA] Face flickering or missing for other avatars on low populated scenes

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4056] opened 2023-01-18 14:27 UTC
Description: 
On low populated scenes where the amount of nearby users is less than 10 the faces of other avatars are often flickering or appear as missing. Issue cannot be observed on scenes with high population of simultaneous users such as Wondermine or ICE Poker. Issue does not disappear after the other avatar is reloaded due to a wearable change.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in using two guests or wallet accounts.
2. Use the `/goto 100,100` command on both logins to teleport to a remote location.
4. On both logins observe the face of the other avatar.

Results:    
On a low population scene the faces of other avatars is flickering or missing.

Expected results: 
On a low population scene the faces of other avatars is present and appears

Notes:    
- Platforms: Windows and MacOS, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot and video for reference.
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/9545c96a-bdaa-437f-bb2a-77efdb29c285)
https://images.zenhubusercontent.com/337227404/51ebc26e-8718-4a6e-9f3e-ff085d0aeeca/2023_01_18_15_19_31.mp4

**Comment by m3taphysics** [comment] 2023-02-02 11:21
Duplicate of #4152

**Closed by m3taphysics** 2023-02-02 11:21 UTC
Labels: bug, minor, new, stream-core
