### ISSUE TITLE
Fix Material and PBRMaterial components 'castShadows' property

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2410] opened 2022-06-03 18:23 UTC
Apparently at some point the `castShadows` property of the `PBRMaterial` and `Material` SDK components stopped working. It should affect the renderers shadow casting based on their material property.

Take into account this is NOT for GLTFShapes, since those shapes material cannot be changed on the fly and are calculated based on the imported GLTF/GLB mesh. This only affects Parametrized shapes.

The pertinent logic is at:
- https://github.com/decentraland/unity-renderer/blob/81a55bae9ac99e848a8ab52ca71a925d4d4b5f20/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs#L34
- https://github.com/decentraland/unity-renderer/blob/81a55bae9ac99e848a8ab52ca71a925d4d4b5f20/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs#L23

With this simple scene code, the problem/effect of that property can be tested:
```
function spawnCube(x: number, y: number, z: number) {
  // create the entity
  const cube = new Entity()

  // add a transform to the entity
  cube.addComponent(new Transform({ position: new Vector3(x, y, z) }))

  // add a shape to the entity
  cube.addComponent(new BoxShape())

  // add the entity to the engine
  engine.addEntity(cube)

  return cube
}

/// --- Spawn a cube ---

const cube = spawnCube(8, 1, 8)

const cube2 = spawnCube(12, 1, 8)

cube.addComponent(
  new OnPointerDown(() => {
    cube.getComponent(Transform).scale.z *= 1.1
    cube.getComponent(Transform).scale.x *= 0.9

    spawnCube(Math.random() * 8 + 1, Math.random() * 8, Math.random() * 8 + 1)
  })
)

let materialWithShadows = new Material()
materialWithShadows.castShadows = true

let materialWOutShadows = new Material()
materialWOutShadows.castShadows = false

cube.addComponent(materialWithShadows)

cube2.addComponent(materialWOutShadows)

let floor = new Entity()

floor.addComponent(new PlaneShape())
floor.addComponent(new Transform({
	position: new Vector3(8,0.2,8),
	rotation: Quaternion.Euler(90,0,0),
	scale: new Vector3(16,16,16)
}))
engine.addEntity(floor)
```

--------------------------
### Acceptance Criteria / Definition of Done
- [ ] Make sure the `castShadows` property works for [`PBRMaterial`](https://github.com/decentraland/unity-renderer/blob/81a55bae9ac99e848a8ab52ca71a925d4d4b5f20/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs) component
- [ ] Make sure the `castShadows` property works for [`Material`](https://github.com/decentraland/unity-renderer/blob/81a55bae9ac99e848a8ab52ca71a925d4d4b5f20/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs) component

**Comment by m3taphysics** [comment] 2022-11-30 17:01
Closed as a duplicate of: https://github.com/decentraland/unity-renderer/issues/3533

**Closed** 2022-11-30 17:00 UTC
Labels: bug, stream-performance
