### ISSUE TITLE
[QA] Channel link redirecting to blank window when posted in another channel

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4435] opened 2023-02-16 15:29 UTC
Description: 
A channel link posted to another channel redirects to the correct channel, but the chat window appears blank. This issue does not affect channel links posted elsewhere.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in with a wallet account.
2. Open up the Chat menu from taskbar and go to any channel. In there post a link to another channel (# followed by the channel name).
3. Click on that channel link.
4. Observe the chat window.

Results:    
Clicking on the channel link redirects to a blank window.

Expected results: 
Clicking on the channel link redirects to a window with correctly shown chat history.

Notes:    
- Platforms: Windows, web and desktop, wallet login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/2253772d-959f-4313-9383-e6107fe1ac8f/2023_02_16_16_15_36.mp4

**Comment by sandrade-dcl** [comment] 2023-07-13 10:02
I'm not able to reproduce it at the moment. I will pass the issue to QA again in order to confirm if it still happens or maybe it was already fixed in recent months.

**Closed** 2023-07-18 09:05 UTC
Labels: bug, medium, stream-social
