### ISSUE TITLE
Creating a new avatar with a wallet starts in the "Collectible" section

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4135] opened 2023-01-26 13:53 UTC
A new user that connected using web3 will be greeted with this when entering for the first time:
![20230126_105321.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/16230cbb-e2a2-4a4a-b644-6abbdb05ad80)
This is not an optimal experience, the user's first interaction should be full of options for customizing their experience, not a prompt to buy things.

Acceptance criteria:
* When entering with a web3 wallet, the first tab should be the "Head" tab, as it is for new guests.

**Comment by olavra** [comment] 2023-02-16 12:26
I think this must be body type right?

**Comment by kwssbocian** [comment] 2023-07-19 12:03
Cannot reproduce - issue no longer occurs since the introduction of the new backpack. Now character creation for new wallet accounts starts at the body shape selection. Closing
![image](https://github.com/decentraland/unity-renderer/assets/110463715/e188fef0-44de-4d44-affc-fa9948046956)

**Closed by kwssbocian** 2023-07-19 12:03 UTC
Labels: stream-social
