### ISSUE TITLE
Black screen of death frequently seen in Chrome

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#1477] opened 2021-11-06 18:57 UTC
in the last few weeks i've started seeing quite frequent "black screen" crashes in the player.
The whole browser screen goes black, although if there was streamed audio i still hear that.

I have only seen these in Chrome (I'm on Windows 10) with latest nVidia drivers, latest Chrome.
I usually am doing something when it crashes.  Here are things I have seen it happen when I do:

- running,
- opening the Backpack
- hitting Esc to get out of chat mode

I haven't seen this in Brave, despite trying.  it either doesn't happen in Brave, or is much more rare.

I tried removing nearly all my Chrome extensions (even ones that I do have in Brave)

i've seen this both in the Conference Center (SDK scenes) and in District X (Builder scenes)

A speculation:  when i hold completely still I do see occasional brief flashes of black, maybe the crash is the conjunction of that happening when i'm active?

**Comment by olavra** [comment] 2021-11-08 13:44
Could you please attach some console log when this happens again?

**Comment by cfravel** [comment] 2021-11-08 20:22
Here is one example, i was just running around in the conference center, jumping sometimes
[1477 Black Screen console log.txt](https://github.com/decentraland/unity-renderer/files/7499886/1477.Black.Screen.console.log.txt)
.

**Comment by cfravel** [comment] 2021-11-08 20:31
Here is another instance.
I was in my booth i the Museum District,  at https://play.decentraland.org/?island=I3ou8j&position=21%2C78&realm=loki
and i chatted "hi" to another avatar, hit escape to be able to use the "4" key to wave, it crashed when i hit 
[1477 Black Screen console log 2.txt](https://github.com/decentraland/unity-renderer/files/7499965/1477.Black.Screen.console.log.2.txt)
4

**Comment by cfravel** [comment] 2021-11-08 20:44
A third incident when running north at https://play.decentraland.org/?island=I3p5xn&position=-6%2C32&realm=loki
This time it put up a note that debugging was disconnected, and went back to the login screen.
So this is sort of different case, probably
[1477 Black Screen console log 3.txt](https://github.com/decentraland/unity-renderer/files/7500044/1477.Black.Screen.console.log.3.txt)

**Comment by cfravel** [comment] 2021-11-08 20:56
Here is another black screen crash, i was exploring buildings in Crypto Valley, at
https://play.decentraland.org/?island=I3pdt9&position=57%2C17&realm=lok
[1477 Black Screen console log 4.txt](https://github.com/decentraland/unity-renderer/files/7500103/1477.Black.Screen.console.log.4.txt)
i

**Comment by cfravel** [comment] 2021-11-08 20:58
Here is what the screen looks like by the way...

![image](https://user-images.githubusercontent.com/21015643/140817112-b5e307a9-108a-405d-ac23-a89e687d2cc5.png)

**Comment by cfravel** [comment] 2021-11-13 18:38
another....
[1477 Black Screen console log 5.txt](https://github.com/decentraland/unity-renderer/files/7532551/1477.Black.Screen.console.log.5.txt)

**Comment by cfravel** [comment] 2021-11-14 20:34
Another, just standing still for some time inworld (Chrome)
[1477 Black Screen console log 6.txt](https://github.com/decentraland/unity-renderer/files/7534612/1477.Black.Screen.console.log.6.txt)

**Comment by cfravel** [comment] 2021-11-14 20:37
I have only seen this in Chrome.
I have seen it usually within an hour or two even when the avatar is completely idle.
I've seen it as soon as 4 minutes of relogging.

I have left Brave up inworld overnight with no probems.

I have seen this in Chrome on more than one Windows 10 machine.

Patmacs told me last night he'd had similar experience, so I also doubht it is anything to do with me or my setup.

**Comment by olavra** [comment] 2022-01-14 02:00
@cfravel since this, we have introduced several changes that may have fix this problem. Could you please confirm if this is still happening to you?

**Comment by pravusjif** [comment] 2022-01-20 22:15
Recopilation of facts known to date:
- The crash happens with incognito guest and different wallets as well, so it's not a problem with the user profile / wallet
- The crash happens regardless of the realm
- The crash happens regardless of the browsers
- Reportedly the crash happens in different computers (if that's really the case then the Double-GPU possible trigger wouldn't be the problem...)

-----

I checked the 6 log files provided and gathered the logs that seem suspicious or interesting, ignoring the ones we normally get in runtime (compared with a fresh log of my own):

**Log1:**
`8[.WebGL-00003C5821092300] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).`

`/?island=I3onqk&position=19%2C103&realm=loki:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`

**Log2:** 
`8[.WebGL-00003C58B3892900] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).`

`/?island=I3ou8j&position=21%2C78&realm=loki:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`

`3rollbar.min.js:1 video: ERROR PIPELINE_ERROR_DECODE: {"causes":[],"data":{},"stack":[{"file":"media/mojo/clients/mojo_video_decoder.cc","line":471}],"status_code":271,"status_message":""}
rollbar.min.js:1 video: ERROR PIPELINE_ERROR_DECODE: {"causes":[],"data":{},"stack":[{"file":"base/bind_internal.h","line":609}],"status_code":271,"status_message":""}`

**Log 3:**
`8[.WebGL-0000466814B59B00] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).`

**Log 4:**
`8[.WebGL-00003F8613FD2A00] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).`

`/?island=I3pdt9&position=57%2C17&realm=loki:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`

`rollbar.min.js:1 video: ERROR PIPELINE_ERROR_DECODE: {"causes":[],"data":{},"stack":[{"file":"media/mojo/clients/mojo_video_decoder.cc","line":471}],"status_code":271,"status_message":""}`

**Log 5:**
`8[.WebGL-00001EC03EB74600] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).`

`play.decentraland.org/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`

**Log 6:**
`8[.WebGL-000037AE05717100] GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).`

`play.decentraland.org/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`

-----

I'm guessing the `CONTEXT_LOST_WEBGL` error is probably AFTER the crash and it's not the culprit, but can't be sure.
`GL_INVALID_OPERATION` appears to be the only error that is present in all the logs (and not in my logs when running the app).

There are some explanations at https://www.khronos.org/opengl/wiki/OpenGL_Error that may give some clue. 

Further debuging is needed.

**Comment by davidejensen** [comment] 2022-05-05 08:24
This issue will have an high estimate due to the fact that there isn't a solid way of constantly reproducing the issue, it is also now known if this still happens

**Comment by davidejensen** [comment] 2022-05-23 11:45
@pravusjif highly doubt that the GL_INVALID_OPERATION is where we should look, that is just a Warning, I've seen that every session has that and even when I go in Decentraland on webgl I see it.

**Comment by davidejensen** [comment] 2022-05-23 11:45
@cfravel Is the problem still happening?

**Comment by cfravel** [comment] 2022-05-23 14:28
I have not seen it for quite some time now.  Perhaps not since the January changes.  Thank you.  I will open a new ticket referencing this one if I see it again.

**Comment by davidejensen** [comment] 2022-05-23 14:30
Perfect, closing it for the moment then, thanks for the response

**Closed by davidejensen** 2022-05-23 14:30 UTC
Labels: bug, need validation, critical
