### ISSUE TITLE
NFTs with animated gif thumbnails have stopped showing thumbnails

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#3492] opened 2022-11-12 17:06 UTC
Until recently, my NFTs that have animated gifs for their "thumbnails" have displayed properly in the Unity Cafe and in The Gallery in the Conference Center.

For approximately the last few weeks I've been noticing that they try for awhile (spinning dots) then just turn white.

Additionially, if yoiu hover and click to "Open UI", the UI also shows no thumbnail.

Steps to reproduce:
Go to https://play.decentraland.org/?position=14,100
Go into the Cafe
See 5 NFTShape displays, 3 on north wall, two on east wall.
// expected:  after some seconds they show an animated thumbnail.  They have for many months in the past
// actual:  now the thumbnail is never displayed

Here is an example of such an NFT:
https://opensea.io/assets/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/45212788081105388007521116546269099584358446490568136574020829712102937591818

The animated GIF is large, so I wonder if there is simply a new, shorter timeout on the GIF loading than before.

![image](https://user-images.githubusercontent.com/21015643/201485878-800fc6d5-ac44-4f7b-abc7-afec874cb834.png)

**Comment by leanmendoza** [comment] 2022-11-15 12:25
With these pair of builds of August, 31st the issue still happens:
https://play.decentraland.org/?position=16%2C101&realm=artemis&kernel-version=1.0.0-2962066080.commit-0d7454e&renderer-version=1.0.51685-20220831135256.commit-e5429a6&island=I4ykb

**Comment by leanmendoza** [comment] 2022-11-15 15:31
This is happening because the NFT is being resolved by a `WEBP` file instead of an animated gif.

I share the test scene that also has the reproduction of this issue: 
https://sdk-test-scenes.decentraland.io/?position=-103%2C102&realm=LocalPreview&LOS=1

**Closed** 2022-11-15 20:48 UTC
Labels: new
