### ISSUE TITLE
Streaming music doesn't resume after using the Backpack

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#1479] opened 2021-11-06 19:28 UTC
Steps to reproduce:
1. Go to a scene that has streaming music, such as the Unity Cafe in the Conference Center, at 14,100
2. Open the backpack // hear backpack music
3. Close the backpack
// Expected: music stream resumes
// Actual:  silent.

To get the music back, you must either leave the scene and return to it, or relog.

I'm hearing this on Windows 10 in both Chrome and Brave.

**Comment by olavra** [comment] 2021-11-08 13:56
We have been testing this scene and the music stops without entering the backpack. Which streaming service are you using?

**Comment by cfravel** [comment] 2021-11-08 21:26
I am running a node media server on a droplet at Digital Ocean.

By default,, when no event is live in the Cafe, my nms iis set to pass through a Blues internet radio stream .
Yes, sometimes it cuts out, but that is pretty rare

On weekends, DJ Rosa's stream is selected instead, using the DJ Console.  
Her stream is Virtual DJ to Shoutcast to my server.

Both of these live stream sources are having this problem with the sound not resuming when you toggle into and out of the backpack.

During testing i get it restarted most quickly by running out of the scene to the north (like to 14,99 ) and then back into the scene 14,100.
To me this says that the streams are working ok except for this Backpack issues.

By contrast, if my nms is being asked for mp3 files stored on the server, the backback doesn't break the audio. -- when I return out of the backback, the mp3 resumes.

This does NOT occur in the Crypto Valley Art Gallery, nor in London Underground when it doesn't have an event.
I'm guessing they are playing mp3 playlists, not based on internet audio streams as a source.

I don't think this used happen.
In the past I believe that i've changed my wearables at our dance events with live streams without the streams not resuming.

**Comment by xavi-dcl** [comment] 2022-12-27 22:23
@kwssbocian could you please verify this is still happening / reproducible in that scene?

**Comment by kwssbocian** [comment] 2023-01-05 12:20
@xavi-dcl Cannot reproduce the issue. On web and desktop opening and closing the backpack did not cause the music to stop.

**Closed** 2023-02-20 15:16 UTC
Labels: bug, need validation, minor, stream-core
