### ISSUE TITLE
SDK UI Canvas does not adapt to window resolution

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#814] opened 2021-07-16 09:24 UTC
The UIs generated by developers through the SDK does not adapt well to window size changes.

@decentralgames
"When playing, resizing the screen to 50% and then later slowly getting it back to a larger state is causing the bottom UI to get fixed in place instead of flexing."
![image (2).png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/8a2c3c4c-0edf-4e11-87d9-d21c4d4ba051)
![image (3).png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/c6f7b4e7-803d-4c5e-a795-82c516618c72)

**Comment by nearnshaw** [comment] 2021-07-27 16:50
This is a duplicate of an issue that was reported a few months back:

https://app.zenhub.com/workspaces/sdk-60febfe80dcd78000f01aca0/issues/decentraland/sdk/19

**Comment by menduz** [comment] 2021-08-17 13:59
Hello, why is this related to the ECS? The UIs are sent as percentages all times. There should not be any change from the ECS in % if the screen changes sizes

**Comment by Kinerius** [comment] 2021-08-17 14:04
The actual problem is related to the Unity implementation of the UI.
With @BrianAmadori we both agreed that the best approach to fix this issue was raising a "ScreenResize" event from kernel and listening to said event to fix the already rendered UI.

**Comment by menduz** [comment] 2021-08-17 14:21
Please do not tint kernel for this fix. Fix it entirely inside unity

**Closed** 2021-08-23 13:44 UTC
Labels: bug, minor, sdk, good first issue
