### ISSUE TITLE
[QA] Empty list message for Collectibles tab disappears shortly after opening

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3469] opened 2022-11-10 11:28 UTC
Description: 
The Empty list message for the Collectibles tab, that is shown when an account has no NFT wearables in possession, disappears a fraction of a second the tab is opened. This results in the Collectibles tab appearing blank.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in on a wallet account that possesses no NFT wearables.   
2. Open up the Backpack and navigate to the Avatar -> Collectibles tab.
3. Observe the contents of the Collectibles tab.

Results:    
Collectibles tab empty list message disappears.

Expected results: 
Collectibles tab empty list message remains on screen.

Notes:    
- Platforms: Windows, web and desktop, wallet login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.
![11.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/52ac6c4c-b77f-41ff-9c80-1a17db8f5a81)

**Comment by aixaCode** [comment] 2023-07-10 11:02
@kwssbocian Is this still an issue with new backpack?

**Comment by kwsskulinski** [comment] 2023-07-11 11:09
Closing, as the issue is no longer present in the new backpack.

**Closed by kwsskulinski** 2023-07-11 11:09 UTC
Labels: bug, need validation, major, stream-social
