### ISSUE TITLE
GIFs used in NFTShapes are miscolored

### ISSUE THREAD

**Issue by dzsunyec** [decentraland/unity-renderer#104] opened 2021-02-02 15:51 UTC
## GIF colors are washed out when linked through and NFTShape ##
It most probably has to do with the gif compression we are using, as checking with an online GIF compression tool, didn't seem to change the colors nearly as much. Are we sure we are not gamma correcting twice or using the wrong color space when converting GIFs?

Scene code to check the color difference:
[https://app.zenhub.com/files/220994476/1aa94989-0c53-4826-9988-10291b17b7e5/download](https://app.zenhub.com/files/220994476/1aa94989-0c53-4826-9988-10291b17b7e5/download)

The problem:
![gif_wahsed_out.png](https://images.zenhubusercontent.com/5f8807a30cc242388d0d392c/ace6119c-f027-4748-8322-09670510076a)

Even if I reduce the colors to 16 and the pixelsize to 128x128 the colors (In the tool below ), the 1.5 MB gif turns into 76 KB, but the colors still remain the same vibrant ones as the original.

Tool to check different compressions (example whale gif atteched):
[https://ezgif.com/optimize](https://ezgif.com/optimize)
![whale.gif](https://images.zenhubusercontent.com/5f8807a30cc242388d0d392c/2eb1ea49-31c1-4a41-8bf6-4a215060af2d)

**Comment by BrianAmadori** [comment] 2021-03-31 14:33
Debugged and confirmed that the issue is that the GIF textures created from JS side are in the wrong color space (linear). This doesn't happen using the UniGif importing path.

Possible solutions:

* Find the way to make `texImage2D` apply the sRGB compliant texture <- The more elegant one
* Manually transform the pixels to sRGB from the gif worker
* Apply an alternative shader (or shader keyword) to render the gif material that's enabled when the gifuct code path is active.

**Comment by xavi-dcl** [comment] 2022-12-27 22:22
Closing as PR from Brian was merged. If it still happens please open a new one.

**Closed by xavi-dcl** 2022-12-27 22:22 UTC
Labels: bug, need validation, minor, tech art, stream-core
