### ISSUE TITLE
Sometimes, a non friend person remains in the friend list

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2312] opened 2022-05-16 14:48 UTC

**Comment by xavi-dcl** [comment] 2022-12-07 12:06
@kwspgoliasz could you please verify and improve description?

**Comment by kwssbocian** [comment] 2022-12-09 10:49
@xavi-dcl Cannot reproduce. During retesting no issue with incorrect or leftover entries in the friends list occurred

**Comment by xavi-dcl** [comment] 2022-12-09 12:08
Closing as it cannot be reproduced.

**Closed by xavi-dcl** 2022-12-09 12:08 UTC
Labels: bug, stream-social
