### ISSUE TITLE
Walking bug

### ISSUE THREAD

**Issue by CorneliusMay** [decentraland/unity-renderer#2600] opened 2022-04-23 11:07 UTC
### What happened?

Avatar moves even when no buttons on the keyboard are pressed. Pressing buttons causes the Avatar to move in the correct direction, but releasing the button causes the Avatar to again move in the same direction. Direction always seems to be diagonally forwards and left.

### Steps to reproduce

This error occurs every time I log in using the desktop application, irrelevant of if I am signing in with my wallet or as a guest. Signing in through the browser login does NOT cause this issue.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD FX(tm)-8350 Eight-Core Processor 

### GPU

NVIDIA GeForce GTX 970 4043MB

### RAM

16283MB

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

desktop-main.commit-7b08a86

### Realm

dg

### NameTag

Leo#956f

**Comment by JorgeDecentraland** [comment] 2022-07-13 11:39
The issue was fixed, can you confirm if you can still reproduce it?

**Comment by JorgeDecentraland** [comment] 2022-07-27 11:47
Closing the issue due to the lack of user's response

**Closed by JorgeDecentraland** 2022-07-27 11:47 UTC
Labels: new
