### ISSUE TITLE
Invisible ground colliders in Conference Center and University

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#169] opened 2021-02-16 04:57 UTC
This is a long standing bug that i really need to get help resolving.
There are colliders in some locations in the conference center, and I've found one that extends into the University.
They really interfere with dancing in the Unity Cafe, and with access to certain OnClick/OnPointerDown interactions.

These colliders are present even in entirely empty or non-deployed parcels, so they are not due to anything in a deployed scene.
Two speculations on my part:  
a. they might be something like a ground-level calculation rounding error (note that these scenes are pretty far north).
b. they might be an effect from a neighboring scene, but that seems far fetched.

Here are two YouTube video that show you places where some of them are, including in some completely empty scenes and undeployed land, and demonstrates their effect inworld.

1. https://www.youtube.com/watch?v=tvcbvSTtseg
Shows colliders in the Unity Cafe area, even when that scene has been completely emptied of content
Shows colliders at the southwest corner of the Conference Centter, in a scene which I'm leaving empty for you to test, and that also shows that the colliders extend into undeveloped land in the SE corner of the University district estate, a completely different estate and scene.

2. https://youtu.be/VoOYB8bOqq8
This video shows a pair of colliders just inside the columns of the main entrance gate of the Conference Center.
The gate itself has no colliders FYI, as shown in the video.

**Comment by cfravel** [comment] 2021-03-23 00:43
Confirming that this is ttill happening as of 3/21/2021

**Comment by sandrade-dcl** [comment] 2021-08-13 15:43
I have noticed it is currently happening in the coord (11,95) and, debugging with the Unity editor, I have seen the problem is provoked by an entity loaded in the parcel (15,95). Please see the attached imege;

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/b6e94a0f-b618-4c85-9efe-f5c57808741a)

So it seems to be something related to the code of the scene that seems to be created some non-visuals colliders.

**Comment by olavra** [comment] 2021-08-30 13:48
Closing this issue, if the problem persist, please let us know

**Closed by olavra** 2021-08-30 13:48 UTC
Labels: bug, need validation, minor, sdk

**Comment by cfravel** [comment] 2022-01-31 03:38
@sandrade-dcl 
Thanks for the Unity Debugger image, this helps a lot.
I think i may have several of these situations near these modular buildings.
Is this Unity Debugger something I could use to look for them?

By the way, the preview dosn't show colliders that are out of bounds of a scene, like it does visible items.
It probably should.
