### ISSUE TITLE
Some wearables are failing AB conversion

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1286] opened 2021-10-01 18:29 UTC
In this manual-conversion of all the wearables to asset bundles, I detected 3 wearables used in production that aren't converting successfully, we should convert them in an isolated way and see what's their problem. If we can fix it let's upload them to the S3.

Target wearables:
- [ ] QmRUVUAn32awrGq2Sy6YTzXc6WVXD31pUunyPAjEZDw24P (I saw this wearable used by many users)
- [ ] QmVkmjdkpqVRob5TDfjzVvDHWpMCJzgSJFPizrrgivt4vJ
- [ ] QmZj8e4SYCGsSNzEzjLsyfosyVpUkMSvsNicMLxXPHGXKL

Also check this other related issue: https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/278

**Comment by olavra** [comment] 2021-10-11 14:57
this is a duplicate of #278

**Closed by olavra** 2021-10-11 14:57 UTC
Labels: new
