### ISSUE TITLE
Under certain conditions, scenes can show as "Unnamed" in the MiniMap even if their scene.json has a Title

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#1475] opened 2021-11-06 06:41 UTC
If you use the fullpage map to go to a scene that has a Title, (and wait for the title to show up on the Map hover point), the title will show on the minimap.
But if you use a URL with coordinates, or if you /goto to go directly to a scene, its title in the Minimap can be "Unnamed".
Running to an adjacent, titled scene and back can cause the names to show up.
I have seen this in both Chrome and Brave.
Examples of scenes that demonstrate this are:
14,100    Unity Cafe in the Conference Center
-79,51     Rizk Amusement Park in District X

Some scenes, like -76,47 Geckos on the Beach, seem to give their titles readily.

**Comment by kwssbocian** [comment] 2023-02-22 14:33
Cannot reproduce. Issue no longer occurs for the mentioned scenes and for various other random ones. Closing

**Closed by kwssbocian** 2023-02-22 14:33 UTC
Labels: bug, minor, stream-core
