### ISSUE TITLE
Issues with the emotes implementation on the development configuration

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3027] opened 2022-09-13 10:11 UTC
**Description:**
A couple of issues with the emote implementation can be observed on the development configuration. The aforementioned issues are:

- **lack of preview for the emotes in the Backpack** - https://images.zenhubusercontent.com/337227404/89dfef26-1d4a-493f-84ec-d1cfb5089552/_3027_preview.mp4;

- **using the emotes in-game cause the avatar's movement animation to become broken** - https://images.zenhubusercontent.com/337227404/f7447ced-1225-442f-a458-b80265380efc/_3027_movement.mp4.

Regarding the second issue, after the emote is used, the avatar begins sliding instead of walking when moved. Using the jump after the issue occurs, temporarily restores regular movement animation, however, the avatar begins sliding again after walking for a few seconds.

**Steps to reproduce:**

1. Load into the development configuration as a guest or via a wallet.
2. Open the Backpack menu ('I').
3. Go to the Emotes section.
4. Set any emote.
5. Observe the issue with the preview.
6. Exit the menu.
7. Use the set emote.
8. Move the avatar.
9. Observe the issue.

**Results:**
Using the emotes causes the avatar's movement animation to become broken. Moreover, no previews are displayed when changing the emotes in the backpack.

**Expected results:**
The emotes are fully functional on the development configuration.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs only on the development configuration.

- On the wallet account, the preview can sometimes be partially displayed before freezing during the animation.

- Please see the attached videos for reference.

- Platform: Web Client

**Comment by JorgeDecentraland** [comment] 2022-10-12 11:23
@kwspgoliasz can you still reproduce this?

**Comment by kwspgoliasz** [comment] 2022-10-12 11:44
@JorgeDecentraland Neither of the issues mentioned in the ticket can be reproduced. It would seem that the other emote updates fixed the issues on the development configuration.

**Comment by JorgeDecentraland** [comment] 2022-10-18 12:11
Closing the issue as we cannot reproduce it

**Closed by JorgeDecentraland** 2022-10-18 12:11 UTC
Labels: major, new, defect
