### ISSUE TITLE
[QA] @Mentions issue for wallet logins on webGL

### ISSUE THREAD

**Issue by kwsskulinski** [decentraland/unity-renderer#4861] opened 2023-04-04 09:10 UTC
Description:

On web @mentions for the wallet users do not show the messages with their name as highlighted in yellow and there is no @ icon in the conversation list for the channel the mention was posted in and also in the notifications window. It appears as just a normal message.

Reproduction rate: 

5/5

Steps to reproduce:    

1. Launch DCL on webGL. 
2. Mention a wallet user on ~nearby chat.
3. Observe the issue.
 
Results:    

Mentions are displayed as normal messages.
 
Expected results:

Mentions are highlighted in yellow.
 
Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for production. 
- Please see the attached screenshot for reference.
![Messages.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/5190cd01-3853-4d4a-a00c-30a8f9e16d30)

**Comment by sandrade-dcl** [comment] 2023-07-13 09:49
I'm not able to reproduce it at the moment. I will pass the issue to QA again in order to confirm if it still happens or maybe it was already fixed in recent months.

**Closed** 2023-07-18 09:04 UTC
Labels: bug, medium, stream-social
