### ISSUE TITLE
[QA] Collision issues inside the tram heading for Genesis Plaza station

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2962] opened 2022-09-02 12:50 UTC
**Description:**
Boarding the tram heading towards Genesis Plaza from the middle station results in the player's avatar getting pushed back by invisible collision when reaching and then departing from Genesis Plaza. The issue occurs for all four tram lines connected to Genesis Plaza.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Move towards any of the tram stations connected to Genesis Plaza.
3. Move along the road and enter the tram line heading towards Genesis Plaza from the middle station.
4. Position the avatar in the center of the tram.
5. Wait for the tram to arrive at Genesis Plaza and then depart from it.
7. Observe the issue.

**Results:**
When reaching and leaving the Genesis Plaza tram station the player's avatar gets pushed back by invisible collision.

**Expected results:**
Lack of collision issues when using the tram.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs only on the production configuration.

- The issue does not occur if the player boards the tram at the Genesis Plaza station.

- The issue appears to be more prominent on the Desktop Client and may sometimes not occur on the Web Client.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/dfa66b1d-c485-442d-b8fa-71022e306de7/_2962.mp4.

- Platforms: Windows Desktop Client, Web Client.

**Comment by xavi-dcl** [comment] 2022-11-16 11:30
@kwspgoliasz please validate, and it might be duplicate issue

**Comment by kwspgoliasz** [comment] 2022-11-17 14:31
@xavi-dcl The issue could not be reproduced during the retests.

**Comment by kwssbocian** [comment] 2023-02-24 14:37
Cannot reproduce. Issue no longer seems to occur. Closing

**Closed by kwssbocian** 2023-02-24 14:37 UTC
Labels: bug, minor, stream-core
