### ISSUE TITLE
UI elements are not being rendered in specific games (Intermittent issue)

### ISSUE THREAD

**Issue by QADecentralGames** [decentraland/unity-renderer#1057] opened 2021-08-24 19:04 UTC
This occurs in production and our staging environment, but we confirmed that when we run the code locally it works. Sometimes we get for instance a Poker UI indicator showing the poker hands names disappearing, or the chips assets from our roulette tables disappearing as well. We also tried removing detail object culling but no luck, same issue.

Attaching screenshots.

Poker Issue in production:
![image](https://user-images.githubusercontent.com/87147545/130674634-7838a262-a59c-4eb1-ab3f-36ac9237927d.png)
Poker UI (correct look, running master branch locally):
![image](https://user-images.githubusercontent.com/87147545/130674642-451d13bb-6019-4104-80fe-db2a8aa56d5a.png)
Roulette issue in production:
![image](https://user-images.githubusercontent.com/87147545/130674800-83df944d-27a2-4ded-98de-b6090e8b31f7.png)
Roulette issue (the correct look):
![image](https://user-images.githubusercontent.com/87147545/130674753-cd378d33-a4ff-45a8-8cdc-21cec3b5e8ab.png)

OS: Windows
Explorer: Google chrome (latest version)

**Comment by sandrade-dcl** [comment] 2021-09-03 12:00
More context about this issue (Slack's thread): https://decentralandteam.slack.com/archives/CS8SCNYUV/p1629486303056100

**Comment by sandrade-dcl** [comment] 2021-09-03 15:49
_(Message copied from the slack thread)_

Hi @QADecentralGames! We are trying to debug the roulette's issue and effectively it is happening... the UI of the selected chip is not being activated.

Taking a look to our flow we have not seen anything weird at the moment that could be provoking it, in fact there are a lot of others UIImage loaded in the scene that are being activated correctly. Even we have confirmed that the specific UIImage corresponding to the chip that should be showed is correctly loaded in the scene, but simply nothing is switching it on as visible. For that we think the problem could be in the scene code side.

We would need to see what the scene is doing but we have not access to it. So, in order to have more info and to be able to continue investigating, it would be nice if you could provide us the code file of an example scene where you can isolate the issue and we're be able to review. Would that be possible?

**Comment by BrianAmadori** [comment] 2021-09-08 13:26
Closing because this seems to be fixed on latest version.

**Closed by BrianAmadori** 2021-09-08 13:26 UTC
Labels: bug, major
