### ISSUE TITLE
Desktop: Hardcut FPS when VSync is disabled

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1507] opened 2021-11-12 13:47 UTC
To avoid overload of the CPU/GPU with VSync disabled, we need to put a hard cut of 240hz when we have VSync disabled.

**Comment by Kinerius** [comment] 2021-12-14 15:33
This issue is a duplicate of https://github.com/decentraland/unity-renderer/issues/478

**Closed** 2021-12-14 16:46 UTC
