### ISSUE TITLE
Issues with the functionality of the Ice Poker after changing the realms

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2895] opened 2022-08-23 08:31 UTC
**Description:**
Changing the realm to 'Hera' inside the Ice Poker scene makes the cards disappear from the tables in every realm, resulting in the player not being able to interact with the tables to begin a game.

**Steps to reproduce:**

1. Log into the game through a wallet.
2. Teleport to the Ice Poker - The Stronghold scene (-102,129).
3. Wait for the tables and cards to load.
4. Change the realm to 'Hera'.
5. Observe the issue

**Results:**
Changing the realm to 'Hera' makes the cards on the poker table disappear in every realm.

**Expected results:**
Changing realms has no influence on Ice Poker's functionality.

**Notes:**

- The issue occurs both on the wallet accounts.

- The issue occurs only on production configuration on both the apps and web.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/d51255f2-48c4-4411-89e2-aec62fd4d055/_2895.mp4.

- Platforms: Windows Desktop Client, Windows Web Client, MacOS Desktop Client.

**Comment by xavi-dcl** [comment] 2022-11-16 11:25
@kwspgoliasz can you please validate?

**Comment by kwspgoliasz** [comment] 2022-11-22 10:03
@xavi-dcl The issue still occurs as described in the ticket. Reproduction rate 5/5.

**Comment by xavi-dcl** [comment] 2022-12-19 08:42
Hi. Closing this one after discussing it with SDK team.
The casino scene is complex, and we do not have access to its code. Therefore we cannot even debug properly. Plus there is a chance that not supporting changing realm in the middle of play happens by design.
In general, and especially in this case, users should contact scene creators on scene logic issues. They should debug issues first and if they find it is a DCL platform issue then they can send it to us with more technical detail.
Decentral Games offers a support channel via their Discord.

**Closed by xavi-dcl** 2022-12-19 08:42 UTC
Labels: bug, major, stream-baus
