### ISSUE TITLE
Fix issue loading profiles from Kernel

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/unity-renderer#4470] opened 2023-02-27 19:31 UTC
When Unity needs to load a profile from the kernel the storage is empty. This bug affects getting friends, friendship requests and private chat.

**Comment by eordano** [comment] 2023-02-28 22:56
Can't reproduce with current `dev` branch. I think the issue is now constrained to the "bot" users that were used to test friendships. I think we're safe to close this issue!

**Closed** 2023-03-01 19:59 UTC
Labels: new, stream-social
